# Generated by Django 3.1.7 on 2021-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='../media/images/default-profile-picture.jpg', upload_to='profile_img'),
        ),
    ]
