# Generated by Django 3.1.7 on 2021-04-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapes', '0002_auto_20210405_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='AromaPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.ImageField(blank=True, upload_to='aroma_img')),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aromapictures', to='grapes.grape')),
            ],
        ),
    ]
