# Generated by Django 3.1.7 on 2021-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_evaluation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, choices=[('Vinho Verde', 'Vinho Verde'), ('Trás-Os-Montes', 'Trás-Os-Montes'), ('Douro', 'Douro'), ('Ribatejo', 'Ribatejo'), ('Bairrada', 'Bairrada'), ('DÃO', 'DÃO'), ('Beiras', 'Beiras'), ('Lisboa', 'Lisboa'), ('Terras do Sado', 'Terras do Sado'), ('Alentejo', 'Alentejo'), ('Madeira', 'Madeira')], max_length=20),
        ),
    ]
