# Generated by Django 3.1.7 on 2021-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20210401_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(blank=True, choices=[('Tinto', 'Tinto'), ('Branco', 'Branco'), ('Verde', 'Verde'), ('Rosé', 'Rosé'), ('Espumante', 'Espumante'), ('Licoroso', 'Licoroso')], max_length=10),
        ),
    ]
