# Generated by Django 3.1.7 on 2021-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_auto_20210405_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='photo',
            field=models.ImageField(default='../media/images/default-bottle.png', upload_to='wines_img'),
        ),
    ]
