# Generated by Django 3.1.7 on 2021-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_auto_20210405_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, choices=[('Vinhos Verdes', 'Vinhos Verdes'), ('Trás-Os-Montes', 'Trás-Os-Montes'), ('Douro', 'Douro'), ('Ribatejo', 'Ribatejo'), ('Bairrada', 'Bairrada'), ('Dão', 'Dão'), ('Beiras', 'Beiras'), ('Lisboa', 'Lisboa'), ('Terras do Sado', 'Terras do Sado'), ('Alentejo', 'Alentejo'), ('Madeira', 'Madeira')], max_length=20),
        ),
    ]
