# Generated by Django 3.1.7 on 2021-03-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.ImageField(blank=True, upload_to='producer_img')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.producer')),
            ],
        ),
    ]
