# Generated by Django 3.1.7 on 2021-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_auto_20210331_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerpictures',
            name='pathname',
            field=models.ImageField(default='../media/images/default-barril.jpg', upload_to='producer_img'),
        ),
    ]
