# Generated by Django 3.1.7 on 2021-04-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_auto_20210405_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducerPictures',
            new_name='ProducerPicture',
        ),
    ]
