# Generated by Django 3.1.7 on 2021-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_auto_20210407_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerpicture',
            name='pathname',
            field=models.ImageField(default='../media/images/default-barril.jpg', upload_to='producers_img'),
        ),
    ]
